// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZJGYSaZDC-JDtJEkmnZCU1KFi9-IXzc',
    appId: '1:970844076654:web:93c4444fbd50fee613847f',
    messagingSenderId: '970844076654',
    projectId: 'todo-app-71ba4',
    authDomain: 'todo-app-71ba4.firebaseapp.com',
    storageBucket: 'todo-app-71ba4.appspot.com',
    measurementId: 'G-4L73MCMTVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXKL_mS4K-2WASlJd29bqfUGTj8zA5tM',
    appId: '1:970844076654:android:cc299bae6ef8390e13847f',
    messagingSenderId: '970844076654',
    projectId: 'todo-app-71ba4',
    storageBucket: 'todo-app-71ba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZABu_H61SPss1JX-K6U-KV-P6CCg_Nw',
    appId: '1:970844076654:ios:dd9060ff02eda4e313847f',
    messagingSenderId: '970844076654',
    projectId: 'todo-app-71ba4',
    storageBucket: 'todo-app-71ba4.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZABu_H61SPss1JX-K6U-KV-P6CCg_Nw',
    appId: '1:970844076654:ios:dd9060ff02eda4e313847f',
    messagingSenderId: '970844076654',
    projectId: 'todo-app-71ba4',
    storageBucket: 'todo-app-71ba4.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZJGYSaZDC-JDtJEkmnZCU1KFi9-IXzc',
    appId: '1:970844076654:web:b65df34e94a5fd2f13847f',
    messagingSenderId: '970844076654',
    projectId: 'todo-app-71ba4',
    authDomain: 'todo-app-71ba4.firebaseapp.com',
    storageBucket: 'todo-app-71ba4.appspot.com',
    measurementId: 'G-SY4NHVE18Q',
  );
}
